AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TokyoVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      Tags:
      - Key: Name
        Value: TokyoVPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: TokyoVPC-IGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref TokyoVPC
      InternetGatewayId: !Ref InternetGateway
  FrontendRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref TokyoVPC
      Tags:
      - Key: Name
        Value: TokyoVPC-FrontendRoute
  FrontendRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref FrontendRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  FrontendSubnetA:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 172.16.1.0/24
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: ap-northeast-1
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref TokyoVPC
      Tags:
      - Key: Name
        Value: TokyoVPC-FrontendSubnet-A
  FrontendSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnetA
      RouteTableId: !Ref FrontendRouteTable
  FrontendSubnetC:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 172.16.65.0/24
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: ap-northeast-1
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref TokyoVPC
      Tags:
      - Key: Name
        Value: TokyoVPC-FrontendSubnet-C
  FrontendSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnetC
      RouteTableId: !Ref FrontendRouteTable
  FrontendSubnetD:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 172.16.129.0/24
      AvailabilityZone: !Select
        - 2
        - Fn::GetAZs: ap-northeast-1
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref TokyoVPC
      Tags:
      - Key: Name
        Value: TokyoVPC-FrontendSubnet-D
  FrontendSubnetDRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnetD
      RouteTableId: !Ref FrontendRouteTable
